name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Updated to a more stable version

      - name: Install dependencies
        run: npm install # Install dependencies

      - name: Build the project
        run: npm run build # Builds your project and outputs the files to the 'build' folder
        
      - name: Debug Build Output
        run: ls -la .next

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v3.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "/*"  # Deploy `.next` and required files
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/node_modules/"

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            npm install --production
            npm run build
            tmux kill-session -t trivia_session
            tmux new-session -d -s trivia_session
            tmux send-keys -t trivia_session 'PORT=3000 HOST=0.0.0.0 npm run start' C-m
